name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  run-my-tests:
    runs-on: ubuntu-latest
    services:
      docker:
        # Use the official Docker image with Scala and SBT pre-installed
        image: hseeberger/scala-sbt:11.0.12_1.5.5_2.13.8
        options: --privileged # Required to use Docker within Docker

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test

  
